### ISSUE TITLE
Support for the 'in' syntax to pass multiple values simultaneously

### ISSUE THREAD

**Issue by CraxFelcore** [IharYakimush/comminity-data-odata-linq#57] opened 2023-03-20 08:20 UTC
Is it possible to support the 'in' syntax to filter on multiple values at the same time. The following example shows the desired result: $filter=City in ('Paris', 'Berlin'). This should return to me all records in these cities. I tried to pass these to your backend without success: `Unreadable query has been given Syntax error at position 15 in 'City in ('Paris', 'Berlin')'`

**Comment by IharYakimush** [comment] 2024-10-30 10:47
Duplicate of https://github.com/IharYakimush/comminity-data-odata-linq/issues/31

**Closed as not planned by IharYakimush** 2024-10-30 10:47 UTC
